title: Brume
author: Aigars Dzerviniks
description: It's simple. It's easy to use. It's a Jekyll theme.

markdown: kramdown
kramdown:
  input:  GFM
  use_coderay: true
permalink: /:title

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
